/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upc.poo;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import upc.poo.ui.InterfazUsuario;
import upc.poo.ui.Teclado;

/**
 *
 * @author hector
 */
public class InicialGUI extends javax.swing.JFrame {

    /**
     * Creates new form InicialGUI
     */
    private static boolean gui;
    private static boolean teclat;
    private static boolean inputtxt;
    private Controlador controlador;
    private boolean botonPulsado = false;
    private InterfazUsuario iu;
    public InicialGUI() {
        this.setLocation(400, 250);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Desde Teclat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Desde GUI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Gestor de taules 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public  boolean isGUI(){
        return gui;
    }
    public boolean isTeclat(){
        return teclat;
    }
    public boolean isInputtxt(){
        return inputtxt;
    }
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       // botonPulsado = true;
        gui = true;
        teclat = false;
        inputtxt = false;
        System.out.println("MODE GUI");
        this.setVisible(false);
        try {
            recuperarSesion();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InicialGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Main().crearVentana();
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //botonPulsado = true;
        teclat = true;
        gui = false;
        inputtxt = false;
        System.out.println("MODE TECLAT");
        this.setVisible(false);
        try {
            recuperarSesion();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InicialGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        controlador.setIu(iu);
        try {
            while(!iu.procesaComando(false));
            System.exit(0);
            //  new Main().crearVentana();
        } catch (IOException ex) {
            Logger.getLogger(InicialGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isBotonPulsado() {
        return botonPulsado;
    }

    /**
     * @param args the command line arguments
     */
    
    private void recuperarSesion() throws FileNotFoundException{
        
        int reply = JOptionPane.showConfirmDialog(null, "Vols recuperar les dades de la sessió anterior?", "", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            //Teclado.setComandosIniciales(true);
            controlador = Main.getControlador();
            iu = Main.getIu();
        }
        else {
            //Teclado.setComandosIniciales(false);
            controlador = new Controlador();
            iu = new InterfazUsuario(controlador);
            PrintWriter out = new PrintWriter("ComandosGuardados.txt");
            out.flush();
            out.close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
